name: On Push Run
on: push
env:
  DEVOPS_DIR: devops
jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: python ${{ env.DEVOPS_DIR }}/main.py
      shell: sh
