name: Python Workflow

on:
  schedule:
      - cron: "*/30 * * * *"
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version:  3.10.13  # Change this to the Python version you need

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Change this if your dependencies are listed in a requirements file

    - name: Run Python Script
      run: python src/models.py  # Replace 'your_script.py' with the actual filename

    - name: Commit and Push Changes
      run: |
        git config --global user.email "saravanashanmuganathan35@gmail.com"
        git config --global user.name "saravanans200"
        git add data/result/result_accuracy.csv  # Adjust the path and file name
        git commit -m "Update CSV file"
        git push origin main  # Replace 'main' with your branch name
