name: On Push Run
on: push
env:
  DEVOPS_DIR: src
jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: python src/main.py
      shell: sh
